APPLICATION = ceres

RIOTBASE ?= ../../../RIOT

RIOTBOARD ?= boards
BOARD ?= samr21-xpro-ceres

DIRS += robot_drivers

USEMODULE += robot_drivers

include robot_drivers/Makefile.include
include $(RIOTBASE)/Makefile.include
